name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Upload Entire Project
      uses: actions/upload-artifact@v4
      with:
        name: project-folder
        path: ./

  docker-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v4
    - name: Download Project Folder
      uses: actions/download-artifact@v4
      with:
        name: project-folder
    - name: Extract Version from package.json
      id: extract-version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Log in to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: jcjv
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile \
          --tag jcjv/prometheus-alerting-nextcloud-talk:${{ env.VERSION }} \
          --tag jcjv/prometheus-alerting-nextcloud-talk:latest
    - name: Push Docker Image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        docker push jcjv/prometheus-alerting-nextcloud-talk:${{ env.VERSION }}
        docker push jcjv/prometheus-alerting-nextcloud-talk:latest